export enum ActionType {
    Empty = '',
    View = 'View',
    Edit = 'Edit',
    Sync = 'Sync',
    Role = 'Role',
    Lock = 'Lock',
    Pause = 'Pause',
    Enable = 'Enable',
    UnLock = 'UnLock',
    Import = 'Import',
    Export = 'Export',
    Delete = 'Delete',
    Verify = 'Verify',
    AddNew = 'Add new',
    Publish = 'Active',
    Disable = 'Disable',
    History = 'History',
    Approve = 'Approve',
    Running = 'Running',
    Download = 'Download',
    EditMember = 'Add account',
    ResetPassword = 'ResetPassword',
}