export enum HubFileStateType {
    Error = -1,
    Pending = 0,
    NomPending = 1,
    NomRejected = 2,
    Nominated = 3,
    ConfirmationPending = 4,
    ConfirmationRejected = 5,
    Confirmed = 6,
    ConfirmationCancellationPending = 7,
    ConfirmationCancellationRejected = 8,
    ConfirmationCancelled = 9,
    ObjectionReceived = 10,
    LapsedConfirmation = 11,
    Transferred = 12,
    MeterInstructions = 14,
    WithdrawalNotice = 15,
    AQICorrected = 16,
    AQICorrectedCancell = 17,
    Opening = 18, // U01
    Opened = 19,  // U03
    LostPending = 28,
    Losted = 29,
    Closing = 30, // U01
    Closed = 31,  // U04
    ONAPending = 40,
    RNAAccepted,
    RNARejected,
    MANPending,
    MASAccepted,
    MASRejected,
    ORJPending,
    RRJAccept,
    RRJReject,
    ONJPending,
    ONJAccept,
    RNJAccept,
    JOBPending,
    JRSAccept,
    JRSReject,
    PO1Pending = 100,
    PO1Accepted,
    PO1Rejected,
    PO2Pending,
    PO2Accepted,
    PO2Rejected,
    PO3Pending,
    PO3Accepted,
    PO3Rejected,
    PO4Pending,
    PO4Accepted,
    PO4Rejected,
    PO5Pending,
    PO5Accepted,
    PO5Rejected,
    PO6Pending,
    PO6Accepted,
    PO6Rejected,
    PO7Pending,
    PO7Accepted,
    PO7Rejected,
    PO8Pending,
    PO8Accepted,
    PO8Rejected,

}